### PR TITLE
Fix and simplify DirectoryEntry validation

### PR DESCRIPTION
**Pull request by jeremy-visionaid**
Ensure both the root and left sibilings are considered when checking for duplicate SIDs.

Also, remove redundant lookups.

### CODE REVIEW

**Comment by jeremy-visionaid** [comment]
@ironfede Looks to me like the root should also optionally throw if ValidationExceptionEnabled is set? i.e.

```
        private void LoadChildren(RBTree bst, IDirectoryEntry de)
        {
            if (de.Child != DirectoryEntry.NOSTREAM)
            {
                IDirectoryEntry child = directoryEntries[de.Child];
                // if (child.StgType != StgType.StgInvalid) // Should actually throw?
                {
                    List<int> levelSIDs = new List<int>();
                    LoadChildren(bst, child, levelSIDs);
                }
            }
        }
```

WDYT?

**Review by ironfede — COMMENTED** [review]
@jeremy-visionaid I think thats named used in methods are not 100% representative or their function. For example SiblingIsValid seems to imply it checks for "validity" but it really checks for "existance" of sibling AND do validation. So I think it should be renamed "HasSiblings" and internally throws for validity exception.

**Comment by ironfede** [comment]
> @ironfede Looks to me like the root should also optionally throw if ValidationExceptionEnabled is set? i.e.
> 
> ```
>         private void LoadChildren(RBTree bst, IDirectoryEntry de)
>         {
>             if (de.Child != DirectoryEntry.NOSTREAM)
>             {
>                 IDirectoryEntry child = directoryEntries[de.Child];
>                 // if (child.StgType != StgType.StgInvalid) // Should actually throw?
>                 {
>                     List<int> levelSIDs = new List<int>();
>                     LoadChildren(bst, child, levelSIDs);
>                 }
>             }
>         }
> ```
> 
> WDYT?

I think it should throw.

**Comment by jeremy-visionaid** [comment]
> @jeremy-visionaid I think thats named used in methods are not 100% representative or their function. For example SiblingIsValid seems to imply it checks for "validity" but it really checks for "existance" of sibling AND do validation. So I think it should be renamed "HasSiblings" and internally throws for validity exception.

Hmm, I might take it further and say that the method actually isn't even aware of sibilings - only the caller is, so "HasSiblings" is also arguably misleading. I think perhaps I could just rewrite it to avoid having a boolean return at all.

**Comment by jeremy-visionaid** [comment]
@ironfede I've rewriten to avoid having a bool method, and added another commit on top that fixes the case where an exception was not thrown if the root entry was invalid too.

**Pull request merged**
