### PR TITLE
When saving an OLEProperties container of type 'AppSpecific' which ha…

### PR DESCRIPTION
**Pull request by Numpsy**
…s custom property names present, write a dictinoary property to the output stream

refs https://github.com/ironfede/openmcdf/issues/134

As it stands now, if you read a property set other than SummaryInformation/DocumentSummaryInformation, and then save that back to the file, and that set contains a DictionaryProperty, then said dictionary will be lost.

So - try always writing it for ```AppSpecific``` sets (we don't want to write such a property for Summry/DocSummary).

### CODE REVIEW

**Comment by Numpsy** [comment]
@ironfede @farfilli Any thoughts or comments on how useful this is or if it should be completed now? (I can see about adding a unit test if it's useful)

**Comment by farfilli** [comment]
It's sure useful!

**Comment by Numpsy** [comment]
Test added

**Comment by ironfede** [comment]
Many Thanks @Numpsy ! Merging now.

**Pull request merged**
